const ActionTypes = {
  FETCH_REPOSITORIES: 'STATS/FETCH_REPOSITORIES',
  FETCH_REPOSITORIES_IN_PROGRESS: 'STATS/FETCH_REPOSITORIES_IN_PROGRESS',
  FETCH_REPOSITORIES_FAILED: 'STATS/FETCH_REPOSITORIES_FAILED',
  FETCH_REPOSITORIES_COMPLETED: 'STATS/FETCH_REPOSITORIES_COMPLETED',

  SWITCH_REPO_TYPE: 'STATS/SWITCH_REPO_TYPE'
};

export default ActionTypes;